name: Publish build
on:
  push:
    branches: 
      - master
concurrency: publish-con
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: .
          git-user: barotdeep
          git-password: ${{ secrets.TOKEN }}
          deployment-branch: master
        
