name: Publish build
on:
  push:
    branches: 
      - master
concurrency: publish-con
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 16
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies
      run: npm install
    - name: Deploy
      uses: redkubes/docusaurus-deploy-action@v1
      with:
        source-folder: .
        git-user: barotdeep
        git-password: ${{ secrets.TOKEN }}
        deployment-branch: master
        
